# coding: utf-8

"""
    MemicOS - Inference Server

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.1.0
    Contact: johnny@memicos.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from memicos_inference_client.models.np_steer_method import NPSteerMethod

class TestNPSteerMethod(unittest.TestCase):
    """NPSteerMethod unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNPSteerMethod(self):
        """Test NPSteerMethod"""
        # inst = NPSteerMethod()

if __name__ == '__main__':
    unittest.main()
