apiVersion: apps/v1
kind: Deployment
metadata:
  name: memicos-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memicos-inference
  template:
    metadata:
      labels:
        app: memicos-inference
    spec:
      containers:
        - name: memicos-inference
          envFrom:
            - configMapRef:
                name: inference-config
            - secretRef:
                name: server-secret
            - secretRef:
                name: sentry-dsn
            - secretRef:
                name: hf-token
          ports:
            - containerPort: 5002
          startupProbe:
            httpGet:
              path: /health
              port: 5002
            failureThreshold: 30 # Allow up to 30 failures during startup
            periodSeconds: 60 # Total max startup time = 30min
          readinessProbe:
            httpGet:
              path: /health
              port: 5002
            initialDelaySeconds: 10
            periodSeconds: 30 # Check every 30s during runtime
            timeoutSeconds: 10
            failureThreshold: 5 # 3 failures = not ready
      # TODO: ReadWriteOnce doesn't allow rolling updates. So we don't use a persistent volume for now.
      #     volumeMounts:
      #       - name: model-storage
      #         mountPath: /root/.cache/huggingface # Default HF cache directory
      # volumes:
      #   - name: model-storage
      #     persistentVolumeClaim:
      #       claimName: model-storage
